Repository jenkinsci/pipeline-utility-steps-plugin, pull requests merged in 2020-01, with the labels that each got.

#72 Bump plugin parent POM
  pom.xml
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java
Labels: chore

#71 findFiles exclusions textbox fix
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/fs/FindFilesStep/config.groovy
Labels: bug, ui

#69 Add overwrite parameter to writeYaml()
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep.java
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/help.html
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepTest.java
Labels: enhancement
