Repository jenkinsci/pipeline-utility-steps-plugin, pull requests merged in 2020-06, with the labels that each got.

#78 Use GitHub as the source of documentation
  README.md
  pom.xml
Labels: documentation

#77 [JENKINS-54346] && [JENKINS-55505] Fix stream handling in tee (followup)
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep.java
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStepTest.java
Labels: bug

#76 [JENKINS-42591] && [JENKINS-47060] Add overwrite option to zip step.
  CHANGES.md
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep.java
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepExecution.java
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep/config.groovy
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep/help-overwrite.html
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java
Labels: enhancement
