Repository jenkinsci/pipeline-utility-steps-plugin, pull requests merged in 2021-03, with the labels that each got.

#92 [JENKINS-62928] Zip step should test canonical paths
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepExecution.java
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java
Labels: bug

#87 [JENKINS-63373] writeYaml should support writing a list as multiple d…
  docs/STEPS.md
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep.java
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep/help.html
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepTest.java
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepUnitTest.java
Labels: enhancement

#90 [JENKINS-63720] add returnText option to writeJSON
  docs/STEPS.md
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep.java
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepExecution.java
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/Messages.properties
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep/help.html
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/jenkins/NodesByLabelStepTest.java
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepTest.java
Labels: enhancement

#91 [JENKINS-34734] add exclude option to zip
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep.java
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepExecution.java
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep/config.groovy
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStep/help-exclude.html
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/zip/ZipStepTest.java
Labels: enhancement

#94 allow writeYaml and writeJSON to return text without requiring a node
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep.java
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStep.java
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepExecution.java
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStepTest.java
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/json/WriteJSONStepTest.java
Labels: bug

#85 updated plugin pom to 4.6 and set min jenkins to 2.204.1
  pom.xml
Labels: chore
