Repository jenkinsci/pipeline-utility-steps-plugin, pull requests merged in 2022-11, with the labels that each got.

#172 Remove obsolete FindBugs configuration
  src/findbugs/excludesFilter.xml
Labels: chore

#164 Set split lines for writeYaml to false
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/WriteYamlStep.java
Labels: bug

#167 Added the option to extract files with their permissions from a tar archive
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStep.java
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStepExecution.java
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStep/config.groovy
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStep/help-keepPermissions.html
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/tar/UnTarStepTest.java
Labels: enhancement
