Repository jenkinsci/pipeline-utility-steps-plugin, pull requests merged in 2024-06, with the labels that each got.

#259 Add dependency on Commons Compress library plugin
  pom.xml
Labels: developer

#251 Fix issue with TeeStep and remoting
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/fs/TeeStep.java
Labels: bug

#93 add one param to set charset when read Properties file
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep.java
  src/main/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepExecution.java
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep/config.jelly
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep/config.properties
  src/main/resources/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStep/help.html
  src/test/java/org/jenkinsci/plugins/pipeline/utility/steps/conf/ReadPropertiesStepTest.java
Labels: enhancement
